#!/usr/bin/perl  -W 
# The first line defines the Perl Interpreter
# Written 2014 by DPH
# Updated 8/8/2017

if ($#ARGV==-1) {&usage;}
@dirs = @ARGV;

while (@ARGV) {
    $dir = pop(@ARGV);  
    open(FILE, "ls $dir/*.dat|");
    while (<FILE>) {
	chomp($_);
#	unlink $_ or warn "Could not unlink file $_\n";
	@remove = (@remove, $_);
    }
}
$unlinked = unlink @remove;
print "$unlinked files removed from directories: @dirs\n";



sub setupdir {
    local(@dir)=@_;

    $numargs =  scalar @dir;
    if ($numargs != 2) {&usage();}
    if (!(-d $dir[0])) {die "directory $dir[0] does not exist!\n";}
    if (-e $dir[1]) {die "file/dir $dir[1] already exists!\n";}
    mkdir $dir[1];
}


# @ARGV = &parseARGV(*ARGV,*patterns,*flags);
# &printARGV(*ARGV,*patterns,*flags);


sub usage {
  my $program=$0;    
  if ($0 =~ /\/([^\/\s]+)$/) {$program=$1;}  # \ followed by not slashes.
  print "Program $program takes one or more directories as arguments. It\n";
  print "removes all hnbody data files ending in .dat from all directories\n";
  print "  Example: $program . r? \n\n";
  exit(1);
}
