#!/usr/bin/perl -W
# The first line defines the Perl Interpreter
# Written 05/23/09 by DPH
# Updated 08/08/17 by DPH
# Runs on Linux/Mac

use File::Copy;

@dir=@ARGV;

&setupdir(@dir);
open(FILE, "ls $dir[0]|");
    
while (<FILE>) {
    $file=$_;
    chop($file); # remove newline
    if ($file =~ /\.in$/ || $file =~ /\.hnb$/) {
        copy("$dir[0]/$file","$dir[1]") or die "copy $file failed\n";
        print "  copied $file from $dir[0] to $dir[1]\n";
    }
}
exit(1);
#        if (!(-e $dir[0]/$file)) {die "file $file does not exist!\n";}    


sub setupdir {
    local(@dir)=@_;

    $numargs =  scalar @dir;
    if ($numargs != 2) {&usage();}
    if (!(-d $dir[0])) {die "directory $dir[0] does not exist!\n";}
    if (-e $dir[1]) {die "file/dir $dir[1] already exists!\n";}
    mkdir $dir[1];
}


# @ARGV = &parseARGV(*ARGV,*patterns,*flags);
# &printARGV(*ARGV,*patterns,*flags);


sub usage {
    my $program=$0;
    if ($0 =~ /\/([^\/\s]+)$/) {$program=$1;}  # \ followed by not slashes.
    print "Program $program takes 2 directory arguments.\n";
    print "It creates a directory (second name) and copies the files\n"; 
    print "*.hnb and *.in from the first directory to the second\n";
    print "  Example: $program r1 r2 \n\n";
    exit(1);
}
