#!/usr/bin/perl  -W  
# The first line defines the Perl Interpreter
# Written 12/2009 by DPH

$DPHpath = $ENV{"HOME"} . "/Dropbox/bin/hnbbin";
$studentpath=    $ENV{"HOME"} . "/bin";
@INC =(@INC, "$DPHpath", "$studentpath");
require 'JobControlLib.pl';    # library for Job Control


# General Job Control Program:
# Setup requires a file $searchfile in each directory in which $executable will be run.
# Code finds all instances of $searchfile in all subdirectories of its argument list


$searchfile = "input.hnb";                      # file required for each run
$logfile    = "log.dat";                        # log file required for each run
$executable = "hnbody -l $logfile $searchfile"; # command to run
$CPUs=8;                                        # number of concurrent runs allowed
&main($searchfile, $executable, $CPUs);





