#!/usr/bin/perl  
# The first line defines the Perl Interpreter
# Written 8/4/2017 by DPH

&main;

sub main {
    my $i=0;
    $verbose=0;    # For Debugging: set to 2 or higher
    if ($#ARGV != 2) {&printUSAGE;}
    $num=$ARGV[0];
    $increment = 10**$ARGV[2];
    print "{";        
    while ($num < $ARGV[1]) {
        printf ("%3.2lf,",$num); $i++;
        $num *= $increment;
    }
    printf ("%3.2lf",$num); $i++;    
    print "}\n";
    print "$i values, increment = $increment\n";    
}


sub printUSAGE {
    local($program,$USAGE);
    $program=$0;

    if ($program =~ /\/([^\/\s]+)$/) {$program=$1;}  # \ followed by not slashes.
    $USAGE = <<"end_of_input";

    Program $program takes 3 numbers as arguments and print outs a
    logarithmically-spaced grid of numbers for programs IC and ICsats.    
        $program low high logspacing
        $program 0.1 10 0.3333


end_of_input
    print $USAGE;
    exit();
}
              
