#! /bin/csh
# Program mrm is a safe & easy way to remove multiple files. Pass it a 
# list of files (wildcards OK) and it will echo them back to you and
# wait 10 seconds before eraseing them so you can change your mind!
# To install program mrm (multiple remove):
# 1) Create a \bin directory and put this file inside
# 2) Do "chmod 744 mrm" to give yourself permission to excecute the file
# 3) Go into your .cshrc file and add "~\bin" to your $path variable.
# 4) Type "rehash" and "source .cshrc" to implement these changes.
# Now you should be able to run mrm in any of your directories.

if ($#argv =~ 0) then
   echo "Program mrm (= multiple remove) takes one or more filenames on"
   echo "the command line, lists them, and then gives a 10 second"
   echo "countdown before removing them all. It does not descend into"
   echo "directories. Abort with Control C."
   echo "  Examples: mrm *.o "
   echo "            mrm body*.dat"
   echo "  "
   exit
endif

######ls -Fsd $argv 
echo " " 
ls -Fsd $argv
echo " " 
echo "The above files will be removed in 9 seconds; "
echo "Subdirectories and their contents will be unaffected. " 
echo -n "(Control C to abort) .... "
foreach i (9 8 7 6 5 4 3 2 1)
  echo -n "$i "
  sleep 1
end
echo ""
echo "Beginning remove task"
rm -f $argv
echo "Finished remove task"

